name: test-web

on:
  pull_request:
    branches: main
    paths:
      - 'apps/web/**'
      - '.github/workflows/test-web.yml'

defaults:
  run:
    working-directory: apps/web

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: lasbe/test:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build the Dockerfile
        run: docker build -t ${{ env.DOCKER_IMAGE_TAG }} --build-arg="NEXT_PUBLIC_API_URL_PROD=${{ secrets.NEXT_PUBLIC_API_URL_PROD }}" .

      - name: Run Docker Container
        run: docker run -d --name test -p 3000:3000 ${{ env.DOCKER_IMAGE_TAG }}

      - name: Install dependencies
        run: npm i -g pnpm && pnpm i && pnpm playwright install chromium --with-deps

      - name: Run Playwright tests
        run: pnpm test:e2e

      - name: Stop And Remove Docker Container
        run: |
          docker stop test
          docker rm test

      - uses: daun/playwright-report-summary@v3
        name: "Playwright Reporter"
        with:
          report-file: apps/web/results.json
          comment-title: "ðŸ”Ž í…ŒìŠ¤íŠ¸ ê²°ê³¼"
          job-summary: true
